### ISSUE TITLE
No driver

### ISSUE THREAD

**Issue by ryanvade** [SIUE-SIGR/KIPR-Open#10]
We don't have a bot for launching the balls off of the Tee.

**Comment by TitaniumBear** [comment]
Heyo haven't been very involved since the end of the year, I had a bot going for this, I have no idea if it is still there. I haven't read up on the current rules, but i would figure that picking up the ball of the tee and then shooting it would have been fine. Sorry that i wont be much help as far as getting it wired up, but i had a servo (or motor?) to lift the ball and drop it in front of the launcher, and then the main motor to wind up and fire. Let me know if there is anything i can do to help.

**Comment by ryanvade** [comment]
@TitaniumBear The current driver is too big and violates the game rules.

**Comment by TitaniumBear** [comment]
well that is certainly a problem then hahaha, do you mind linking me the limitations on the size/functions? I might be able to sketch up something for someone to assemble

**Comment by ryanvade** [comment]
@TitaniumBear http://files.kipr.org/kipropen/2016_KO_rules_v1.2.pdf
